(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Library: MTMpcSiso
 * File: MTMpcSiso.typ
 * Author: B&R
 ********************************************************************
 * Data types of library MTMpcSiso
 ********************************************************************)

TYPE
	MTMpcSisoEnhancedPortType : {REDUND_UNREPLICABLE} 	STRUCT  (*Port between function block and non cyclic task class*)
		Link : REFERENCE TO MTMpcSisoEnhanced; (*Self display of function block structure*)
		StatusASync : {REDUND_UNREPLICABLE} UINT; (*Status information of non cyclic operations*)
		StatusQp : {REDUND_UNREPLICABLE} USINT; (*Status information of solution vector*)
		_statemachine : {REDUND_UNREPLICABLE} USINT; (*Internal ASYFUMA var*)
		_result : {REDUND_UNREPLICABLE} USINT; (*Internal ASYFUMA var*)
	END_STRUCT;
	MTMpcSisoEnhancedInternalType : 	STRUCT  (*Internal data of MTMpcSisoEnhanced*)
		FailureMemory : ARRAY[0..99]OF DINT; (*Failure memory of last function block errors (every item) and warnings (item per case)*)
		Warning : {REDUND_UNREPLICABLE} BOOL; (*Function block warning active*)
		Initialized : {REDUND_UNREPLICABLE} BOOL; (*First init accomplished*)
		InputError : {REDUND_UNREPLICABLE} BOOL := 0; (*0 => everything ok; 1 => imperfect/wrong fub interface allocation*)
		SolverError : {REDUND_UNREPLICABLE} INT := 0; (*Error number of solver*)
		TotalAdd : {REDUND_UNREPLICABLE} INT := 0; (*Total number of constraints added*)
		TotalDrop : {REDUND_UNREPLICABLE} INT := 0; (*Total number of constraints dropped*)
		InitStatus : {REDUND_UNREPLICABLE} BOOL := 0; (*Status == 1 => initialization*)
		SolverStatus : {REDUND_UNREPLICABLE} BOOL := 0; (*Status == 1 => solver busy*)
		PostCtrlStatus : {REDUND_UNREPLICABLE} BOOL := 0; (*Status == 1 => post control busy*)
		UpdateOld : {REDUND_UNREPLICABLE} BOOL := 0; (*Temp. mem.*)
		SystemReset : {REDUND_UNREPLICABLE} BOOL := 0; (*System behavior chronicle temp. mem.*)
		SystemResetOld : {REDUND_UNREPLICABLE} BOOL := 0; (*System behavior chronicle temp. mem.*)
		CtrlHorReduced : {REDUND_UNREPLICABLE} UDINT; (*Amount of merged control horizon blocks*)
		SlideCount : {REDUND_UNREPLICABLE} UDINT := 0; (*Internal counter to prevent control horizon overrun during shift op*)
		DRAM : {REDUND_UNREPLICABLE} UDINT; (*Displays free DRAM of the control computer*)
		CtrlTimeStamp : UDINT; (*Expired task class cycles to last control action *)
		CtrlMode : USINT; (*0 => promt contr. (no control in init); 1 promt contr. (feed forward in init); >1 => time definite contr. *)
		InitTime : {REDUND_UNREPLICABLE} UDINT; (*Time requirement of initialization procedure (ms)*)
		SolverTime : {REDUND_UNREPLICABLE} UDINT; (*Time requirement of solver (ms)*)
		PostCtrlTime : {REDUND_UNREPLICABLE} UDINT; (*Time requirement of trajectory generation (ms)*)
		ProcessTime : {REDUND_UNREPLICABLE} UDINT; (*Measured cycle time of controlled system (ms)*)
		CycleTime : {REDUND_UNREPLICABLE} LREAL; (*Measured cycle time of controlled system (ms)*)
		EigenvalueMin : {REDUND_UNREPLICABLE} LREAL; (*Min eigenvalue of hessian*)
		EigenvalueMax : {REDUND_UNREPLICABLE} LREAL; (*Max eigenvalue of hessian*)
		ActPrd : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Predicted sequence of controlled variables*)
		ActDeltaPrd : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Predicted rate of controlled variables as sequence*)
		OutDeltaOpt : ARRAY[0..200]OF LREAL := [201(0.0)]; (*Solver access to next optimal solution*)
		StatOpt : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Static optimization part*)
		UpdateActive : BOOL; (*Internal function block update in progress*)
		Scanned : MTMpcSisoEnhancedInternalScdType; (*Allows active control steps during initialization and obj. calculation*)
		StartTime : {REDUND_UNREPLICABLE} TIME; (*Internal time measurement*)
		EndTime : {REDUND_UNREPLICABLE} TIME; (*Internal time measurement*)
		OutMinDragInd : LREAL := 0.0; (*Drag indicator of minimum output variables*)
		OutMaxDragInd : LREAL := 0.0; (*Drag indicator of maximum output variables*)
		Bootkey : {REDUND_UNREPLICABLE} BOOL; (*First init accomplished*)
		Hzp : REFERENCE TO LREAL; (*Memory to define objective*)
		YTransform : REFERENCE TO LREAL; (*Memory to define objective*)
		Hyp : REFERENCE TO LREAL; (*Memory to define objective*)
		HypT : REFERENCE TO LREAL; (*Memory to define objective*)
		H : REFERENCE TO LREAL; (*Memory to define objective*)
		Zin : REFERENCE TO LREAL; (*Memory to define objective*)
		Rin : REFERENCE TO LREAL; (*Memory to define objective*)
		RcnIn : REFERENCE TO LREAL; (*Memory to define objective*)
		Hoy : REFERENCE TO LREAL; (*Memory to define objective*)
		Hoz : REFERENCE TO LREAL; (*Memory to define objective*)
		Hoyz : REFERENCE TO LREAL; (*Memory to define objective*)
		Hcyz : REFERENCE TO LREAL; (*Memory to define objective*)
		L : REFERENCE TO LREAL; (*Memory to define objective*)
		TM1 : REFERENCE TO LREAL; (*Temporary memory*)
		TM2 : REFERENCE TO LREAL; (*Temporary memory*)
		TM3 : REFERENCE TO LREAL; (*Temporary memory*)
		TM4 : REFERENCE TO LREAL; (*Temporary memory*)
		TM5 : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL := [200(0.0)]; (*Temporary memory*)
		TM6 : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL := [200(0.0)]; (*Temporary memory*)
		TMQp : {REDUND_UNREPLICABLE} ARRAY[0..1806]OF INT; (*Temporary memory*)
	END_STRUCT;
	MTMpcSisoEnhancedInternalScdType : 	STRUCT  (*Scanned data of MTMpcSisoEnhanced*)
		SystemRange : {REDUND_UNREPLICABLE} MTMpcSisoSystemRangeType; (*System range of scanned control specific data*)
		NAct : {REDUND_UNREPLICABLE} USINT := 1; (*Number of controlled variables*)
		NOut : {REDUND_UNREPLICABLE} USINT := 1; (*Number of manipulating variables*)
		NDist : {REDUND_UNREPLICABLE} USINT := 0; (*Number of disturbance variables*)
		PrdHor : {REDUND_UNREPLICABLE} UDINT := 100; (*Prediction horizon *)
		CtrlHor : {REDUND_UNREPLICABLE} UDINT := 50; (*Control horizon *)
		OutOperatingPoint : {REDUND_UNREPLICABLE} LREAL := 0.0; (*Adjust static operating points regarded to actuating variables*)
		ActOperatingPoint : {REDUND_UNREPLICABLE} LREAL := 0.0; (*Adjust static operating points regarded to controlled variables*)
		OutMin : {REDUND_UNREPLICABLE} LREAL := 0.0; (*Minimum value for manipulating variables*)
		OutMax : {REDUND_UNREPLICABLE} LREAL := 0.0; (*Maximum value for manipulating variables*)
		SoftConstraint : {REDUND_UNREPLICABLE} BOOL := FALSE; (*Disable enable soft constraint formulation per CV*)
		FIRModel : {REDUND_UNREPLICABLE} BOOL := FALSE; (*Specify if system dynamic (stored as FSR/FIR <=> False/True)*)
		CtrlHorReduced : {REDUND_UNREPLICABLE} UDINT := 1; (*Amount of merged control horizon blocks*)
		ActOld : LREAL := 0.0; (*Former scanned control variable measurement*)
		Act : LREAL := 0.0; (*Scanned control variable measurement*)
		OutOld : LREAL := 0.0; (*Former scanned manipulating variable measurement*)
		OutRef : LREAL := 0.0; (*Scanned reference input of manipulating variables*)
		Out : LREAL := 0.0; (*Scanned manipulating variables*)
		Dist : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Scanned intended sequence of disturbance values*)
		DistOld : LREAL := 0.0; (*Scanned former disturbance values*)
		DistMeasured : LREAL := 0.0; (*Scanned disturbance values*)
		Set : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Scanned intended sequence of reference values*)
		OptStatOld : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Static part of optimization criteria*)
		OutDeltaOptOld : ARRAY[0..200]OF LREAL := [201(0.0)]; (*Former optimal solution *)
		OutDeltaScdOld : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Former scanned delta manipulating variables*)
		OutScdOld : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Manipulating variable chronicle*)
		OutStatActModel : LREAL := 0.0; (*Static part of model based control variables calc. according to Out*)
		ActByOut : LREAL := 0.0; (*Out convolution part of model based control variables calc.*)
		DistDeltaPrd : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Specified delta disturbance variables of system*)
		DistScdOld : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Disturbance variables chronicle*)
		DistDeltaScdOld : ARRAY[0..200]OF LREAL := [201(0.0)]; (*Former scannced delta disturbance variables*)
		DistStatActModel : LREAL := 0.0; (*Static part of model based control variables calc. according to Dist *)
		ActByDist : LREAL := 0.0; (*Dist convolution part of model based control variables calc.*)
		ActScdOld : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Controlled variables chronicle*)
		ActDeltaModel : LREAL := 0.0; (*Predicted delta control variables of next control cycle*)
		ActDeltaMeasured : LREAL := 0.0; (*Measured delta control variables of next control cycle*)
		ActModelBased : LREAL := 0.0; (*Model based calculated control variables*)
	END_STRUCT;
	MTMpcSisoEnhancedPerformanceType : 	STRUCT  (*Control / model quality review of MTMpcSisoEnhanced*)
		InitTimeRatio : {REDUND_UNREPLICABLE} UINT; (*Ratio between initialization and process sample time in %*)
		CtrlTimeRatio : {REDUND_UNREPLICABLE} UINT; (*Ratio between optimization (new control action) and process sample time in %*)
		TotalTimeRatio : {REDUND_UNREPLICABLE} UINT; (*Ratio between total calculation and process sample time in %*)
		ConditionNbr : {REDUND_UNREPLICABLE} LREAL; (*Condition number of hessian according to l2 norm*)
		StatObj : {REDUND_UNREPLICABLE} LREAL; (*Stat. part of objective function*)
		DynObj : {REDUND_UNREPLICABLE} LREAL; (*Dynamic part of objective function*)
		Iter : {REDUND_UNREPLICABLE} DINT; (*Number of iterations*)
		ActDeltaPrd : {REDUND_UNREPLICABLE} LREAL; (*Rate of model based calc. PV's*)
		ActIDeltaPrd : {REDUND_UNREPLICABLE} LREAL; (*Sum of rate of model based calc. PV's*)
		PrdError : {REDUND_UNREPLICABLE} LREAL; (*Prediction errors*)
		PrdAvgError : {REDUND_UNREPLICABLE} LREAL; (*Arithmetic mean of prediction errors*)
		PrdIAError : {REDUND_UNREPLICABLE} LREAL; (*Integral absolute errors of prediction errors*)
		CtrlError : {REDUND_UNREPLICABLE} LREAL; (*Control errors*)
		CtrlAvgError : {REDUND_UNREPLICABLE} LREAL; (*Arithmetic mean of control errors*)
		CtrlIAError : {REDUND_UNREPLICABLE} LREAL; (*Integral absolute errors of control errors*)
		OutVar : {REDUND_UNREPLICABLE} LREAL; (*Variance of manipulating variables (prediction horizon)*)
		ActVar : {REDUND_UNREPLICABLE} LREAL; (*Variance of controlled variables (prediction horizon)*)
		CorrActMeasuredPrd : {REDUND_UNREPLICABLE} LREAL; (*Correlation between PV and IdxP*)
		Slack : {REDUND_UNREPLICABLE} LREAL; (*Contain slack variables if soft constraints are enabled*)
		CycleCount : UDINT := 0; (*Internal counter till system sample time is reached (cycleFactor)*)
		PrdCompleted : {REDUND_UNREPLICABLE} BOOL := FALSE; (*Change from false to true if QP is solved and predictive data is generated => post contr finished*)
		ActIScdDeltaPrd : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL; (*Cummulative sum of predicted control variable rate*)
		ActScdDeltaPrd : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL; (*Predicted control variable rate*)
		PrdErrorScdOld : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL; (*Prediction error FIFO memory (x_measured(k) - x_predicted(k))*)
		CtrlErrorScdOld : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL; (*Control error FIFO memory*)
	END_STRUCT;
	MTMpcSisoParameterType : 	STRUCT  (*MPC parametrization structure*)
		MemMode : BOOL := FALSE; (*TRUE => memory allocation or rather function block operation mode / FALSE => delete memory*)
		CycleFactor : UDINT := 1; (*Adjust sampling time of controlled system (CycleFactor * task class cycle time = sample time of process)*)
		NrDist : USINT := 1; (*Number of measured disturbances*)
		PredictionHorizon : UDINT := 100; (*Prediction horizon*)
		ControlHorizon : UDINT := 50; (*Global control horizon*)
		OutSamplesMerge : USINT := 1; (*Set up quantity of merged output trajectory entries *)
		OutOperatingPoint : LREAL := 0.0; (*Adjust static operating points regarded to actuating variables*)
		ActOperatingPoint : LREAL := 0.0; (*Adjust static operating points regarded to controlled variables*)
		WeightErrorExp : LREAL := 0.0; (*Weight factor take exponential affect on control error*)
		WeightError : LREAL := 1.0; (*Weight factor take linear affect on control error*)
		OutMoveSuppression : LREAL := 1.0; (*Weight factor take linear affect on manipulating variables (0 => no alteration limit till u_min, u_max)*)
		ActDeltaWeight : LREAL := 0.0; (*Weight openloop - closed loop delta control variables prediction amount (only IT Systems)*)
		FIRModel : BOOL := FALSE; (*Specify system dynamic (FSR/FIR <=> False/True)*)
		SoftConstraint : BOOL := FALSE; (*Enable soft constraint formulation per control variable*)
		OutDeltaMin : LREAL := 0.0; (*Allowed minimum rate of manipulating variables*)
		OutDeltaMax : LREAL := 0.0; (*Allowed maximum rate of manipulating variables*)
		OutMin : LREAL := 0.0; (*Absolute minimum value for manipulating variables*)
		OutMax : LREAL := 0.0; (*Absolute maximum value for manipulating variables*)
		ActSoftMin : LREAL := 0.0; (*Soft lower bound constraints of control variables*)
		ActSoftMax : LREAL := 0.0; (*Soft upper bound constraints of conrol variables*)
		PostCtrlDisable : BOOL; (*Disable calculation of predicted output trajectories*)
		OutRespAct0 : REFERENCE TO LREAL; (*FSR/FIR characterize ActValue/Out*)
		DistRespAct0 : REFERENCE TO LREAL; (*FSR/FIR characterize ActValue/Disturbance*)
		SystemRange : {REDUND_UNREPLICABLE} MTMpcSisoSystemRangeType; (*System range of control specific data*)
	END_STRUCT;
	MTMpcSisoLiteInternalType : 	STRUCT  (*Internal data of MTMpcSisoLite*)
		SolverError : {REDUND_UNREPLICABLE} INT := 0; (*Error number of solver*)
		CtrlHorReduced : {REDUND_UNREPLICABLE} UDINT := 1; (*Amount of merged control horizon blocks*)
		CycleCount : UDINT := 1; (*Internal counter till system sample time is reached*)
		InitTime : {REDUND_UNREPLICABLE} UDINT := 0; (*Time requirement of initialization procedure (ms)*)
		SolverTime : {REDUND_UNREPLICABLE} UDINT := 0; (*Time requirement of objective calculation procedure (ms)*)
		CycleTime : {REDUND_UNREPLICABLE} LREAL; (*Cycle time*)
		Warning : {REDUND_UNREPLICABLE} BOOL := 0; (*Temp. mem.*)
		Iter : {REDUND_UNREPLICABLE} DINT := 0; (*Number of iterations*)
		TotalAdd : {REDUND_UNREPLICABLE} INT := 0; (*Total number of constraints added*)
		TotalDrop : {REDUND_UNREPLICABLE} INT := 0; (*Total number of constraints dropped*)
		UpdateActive : {REDUND_UNREPLICABLE} BOOL := 0; (*Temp. mem.*)
		Update : {REDUND_UNREPLICABLE} BOOL := 0; (*Temp. mem.*)
		UpdateOld : {REDUND_UNREPLICABLE} BOOL := 0; (*Temp. mem.*)
		EigenvalueMin : {REDUND_UNREPLICABLE} LREAL; (*Min eigenvalue of hessian*)
		EigenvalueMax : {REDUND_UNREPLICABLE} LREAL; (*Max eigenvalue of hessian*)
		OutMinDragInd : LREAL := 0.0; (*Drag indicator of miinimum manipulating variables*)
		OutMaxDragInd : LREAL := 0.0; (*Drag indicator of maximum manipulating variables*)
		ActPrd : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL := [200(0.0)]; (*Predicted sequence of controlled variables*)
		ActDeltaPrd : {REDUND_UNREPLICABLE} ARRAY[0..199]OF LREAL := [200(0.0)]; (*Predicted rate of controlled variables*)
		OutDeltaOpt : ARRAY[0..200]OF LREAL := [201(0.0)]; (*Solver access to next optimal solution*)
		StatOpt : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Static optimization part*)
		OutDeltaScdOld : ARRAY[0..199]OF LREAL := [200(0.0)]; (*Former delta manipulating variables*)
		DistDeltaScdOld : ARRAY[0..200]OF LREAL := [201(0.0)]; (*Former delta disturbance variables*)
		ActScd : LREAL; (*Scanned controlled variables*)
		ActOld : LREAL; (*Former controlled variables*)
		OutOld : LREAL; (*Former manipulating variables*)
		DistOld : LREAL; (*Former disturbance values*)
		Hzp : REFERENCE TO LREAL; (*Memory to define objective*)
		YTransform : REFERENCE TO LREAL; (*Memory to define objective*)
		Hyp : REFERENCE TO LREAL; (*Memory to define objective*)
		HypT : REFERENCE TO LREAL; (*Memory to define objective*)
		H : REFERENCE TO LREAL; (*Memory to define objective*)
		Hoyz : REFERENCE TO LREAL; (*Memory to define objective*)
		Hcyz : REFERENCE TO LREAL; (*Memory to define objective*)
		L : REFERENCE TO LREAL; (*Memory to define objective*)
		Zin : REFERENCE TO LREAL; (*Memory to define objective*)
		Rin : REFERENCE TO LREAL; (*Memory to define objective*)
		RcnIn : REFERENCE TO LREAL; (*Memory to define objective*)
		TM1 : REFERENCE TO LREAL; (*Temporary memory*)
		TM2 : REFERENCE TO LREAL; (*Temporary memory*)
		TM3 : REFERENCE TO LREAL; (*Temporary memory*)
		TM4 : REFERENCE TO LREAL; (*Temporary memory*)
		TMQp : {REDUND_UNREPLICABLE} ARRAY[0..1806]OF INT; (*Temporary memory*)
		Bootkey : {REDUND_UNREPLICABLE} UDINT; (*Internal usage*)
	END_STRUCT;
	MTMpcSisoSystemRangeType : {REDUND_UNREPLICABLE} 	STRUCT  (*MPC specific function block data range*)
		NActSum : {REDUND_UNREPLICABLE} UDINT := 0; (*Calculated objective size*)
		NOutSum : {REDUND_UNREPLICABLE} UDINT := 0; (*Calculated objective size*)
		NOutSumMerged : {REDUND_UNREPLICABLE} UDINT := 0; (*Calculated objective size*)
		NOutSumMax : {REDUND_UNREPLICABLE} UDINT := 0; (*Calculated objective size*)
		NDistSum : {REDUND_UNREPLICABLE} UDINT := 0; (*Calculated objective size*)
		NDistSumMax : {REDUND_UNREPLICABLE} UDINT := 0; (*Calculated objective size*)
		TempMemMax : {REDUND_UNREPLICABLE} UDINT := 0; (*Temporary memory size of initialization procedure*)
		QpMemMax : {REDUND_UNREPLICABLE} UDINT := 0; (*Temporary memory size of objective *)
		NSoftC : {REDUND_UNREPLICABLE} USINT := 0; (*Number of considered soft constraints*)
	END_STRUCT;
	MTMpcSisoReactorInternalType : 	STRUCT  (*Internal data of MTMpcSisoReactor*)
		V : LREAL; (*Gain MV 1 to CV's*)
		T : LREAL; (*Time constants MV 1 to CV's*)
		d : LREAL; (*Time constants MV 1 to CV's*)
		Td : LREAL; (*Time constants MV 1 to CV's*)
		Tt : UINT; (*Deadtime MV 1 to CV's*)
		xInternal : LREAL; (*Systembehavior CV 1 to all inputs*)
		xOld1 : LREAL; (*Systembehavior CV 1 to all inputs*)
		xOld2 : LREAL; (*Systembehavior CV 1 to all inputs*)
		yOld : LREAL; (*Systembehavior CV 1 to all inputs*)
		CycleTime : {REDUND_UNREPLICABLE} LREAL; (*Cycle time of task class as well as process sample time*)
		yBuffer : ARRAY[0..199]OF LREAL; (*Internal usage*)
		Bootkey : {REDUND_UNREPLICABLE} UDINT; (*Internal usage*)
	END_STRUCT;
END_TYPE
