(*Types of MTTemp*)

TYPE
	MTTempCommunicationType : 	STRUCT  (*Communication type.*)
		FB : USINT; (*Denotes whether FB is DISABLED -> 0 or ENABLED -> 1*)
		Control : USINT; (*Commandos for the controller.*)
		Mode : USINT; (*Mode for the FB*)
		CurrentMode : USINT; (*Heating or Cooling mode.*)
		OPCStatus : USINT; (*Status of the OPC FB.*)
		TuningPhase : USINT; (*Current tuning phase.*)
		MultiZoneStatus : USINT; (*Status of multizone tuning.*)
		CodeInformation : USINT; (*Code information for the ControlStatus*)
	END_STRUCT;
	MTTempPlantInternalType : 	STRUCT  (*Internal plant parameters for heating and cooling.*)
		Heating : MTTempPlantParaInternalType; (*Parameter for the known or identified plant for heating.*)
		Cooling : MTTempPlantParaInternalType; (*Parameter for the known or identified plant for cooling.*)
	END_STRUCT;
	MTTempPlantParaInternalType : 	STRUCT  (*Parameter for Temperature model: PT2 with Td.*)
		Gain : REAL; (*Gain factor. Unit [K/%].*)
		TimeConstant1 : REAL; (*Time constant 1. Unit [s].*)
		TimeConstant2 : REAL; (*Time constant 2 Unit [s].*)
		DelayTime : REAL; (*Delay Time. Unit [s].*)
		PlantType : MTTempPlantEnum;
	END_STRUCT;
	MTTempPlantParametersType : 	STRUCT  (*Parameter for Temperature model: PT2 with Td.*)
		Gain : REAL; (*Gain factor. Unit [K/%].*)
		TimeConstant1 : REAL; (*Time constant 1. Unit [s].*)
		TimeConstant2 : REAL; (*Time constant 2 Unit [s].*)
		DelayTime : REAL; (*Delay Time. Unit [s].*)
	END_STRUCT;
	MTTempPlantType : 	STRUCT  (*Plant parameters for heating and cooling.*)
		Heating : MTTempPlantParametersType; (*Parameter for the known or identified plant for heating.*)
		Cooling : MTTempPlantParametersType; (*Parameter for the known or identified plant for cooling.*)
	END_STRUCT;
	MTTempProfileType : 	STRUCT  (*Profile parameters for heating and cooling.*)
		Heating : MTTempProfileParametersType; (*Profile parameters for heating.*)
		Cooling : MTTempProfileParametersType; (*Profile parameters for cooling.*)
	END_STRUCT;
	MTTempControllerType : 	STRUCT  (*PID parameters for heating and cooling.*)
		Heating : MTPIDParametersType; (*PID parameter for heating.*)
		Cooling : MTPIDParametersType; (*PID parameter for cooling.*)
	END_STRUCT;
	MTTempProfileParametersType : 	STRUCT  (*Profile parameters.*)
		SlewRate : REAL; (*Slew rate of profile in °C/s.*)
		FilterTime : REAL; (*Filter time of profile in s.*)
		DelayTime : REAL; (*Delay time of profile in s.*)
	END_STRUCT;
	MTTempTimeDelayFcnParaType : 	STRUCT  (*Time delay function type.*)
		DelayCounter : UDINT; (*Data for internal use.*)
		ActBufferIndex : UDINT; (*Data for internal use.*)
		ActBufferElements : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
		OldBufferElements : {REDUND_UNREPLICABLE} UDINT; (*Data for internal use.*)
		DelayTimeAct : REAL; (*Data for internal use.*)
		BufferPointer : REFERENCE TO REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempTimeDelayInternalType : 	STRUCT  (*Internal variables of function block MTBasicsTimeDelay.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		DelayTime : REAL; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		InitialValue : REAL; (*Data for internal use.*)
		Enable : BOOL; (*Data for internal use.*)
		TimeDelayFcnPara : {REDUND_UNREPLICABLE} MTTempTimeDelayFcnParaType; (*Data for internal use.*)
	END_STRUCT;
	MTTempPlantEnum : 
		( (*Enum to specify the type of plant.*)
		mtTMP_NO_ELEMENT := 0, (*No element assigned.*)
		mtTMP_1ST_ORDER_LAG_ELEMENT_INT := 2, (*First order lag element with integrator.*)
		mtTMP_2ND_ORDER_LAG_ELEMENT := 3 (*Second order lag element.*)
		);
END_TYPE

(*Types of MTTempController*)

TYPE
	MTTempControllerInternalType : 	STRUCT  (*Internal parameter of function block MTTempController.*)
		SetStartValues : BOOL; (*Data for internal use.*)
		FirstRun : BOOL; (*Data for internal use.*)
		FilterOn : BOOL; (*Data for internal use.*)
		PlantParametersHeatValid : BOOL; (*Data for internal use.*)
		PlantParametersCoolValid : BOOL; (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit [s]*)
		ParametersValid : BOOL; (*Data for internal use.*)
		PIDParametersCoolValid : BOOL; (*Data for internal use.*)
		PIDParametersHeatValid : BOOL; (*Data for internal use.*)
		PIDParameters : MTTempControllerType; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		MaxHeatOut : REAL; (*Data for internal use.*)
		MaxCoolOut : REAL; (*Data for internal use.*)
		ModeObserver : MTTempModeEnum; (*Data for internal use.*)
		Mode : MTTempModeEnum; (*Data for internal use.*)
		StateOld : USINT; (*Data for internal use.*)
		State : USINT; (*Data for internal use.*)
		StateObserver : USINT; (*Data for internal use.*)
		CommunicationInOld : MTTempCommunicationType; (*Data for internal use.*)
		CommunicationInCheck : MTTempCommunicationType; (*Data for internal use.*)
		CommunicationIn : MTTempCommunicationType; (*Data for internal use.*)
		SetCoolOutOld : BOOL; (*Data for internal use.*)
		SetHeatOutOld : BOOL; (*Data for internal use.*)
		Output : REAL; (*Data for internal use.*)
		PID : MTTempPIDType; (*Data for internal use.*)
		TempOld : REAL; (*Data for internal use.*)
		PlantParameters : MTTempPlantType; (*Data for internal use.*)
		ActTempDerivative : REAL; (*Data for internal use.*)
		ActTempFiltered : REAL; (*Data for internal use.*)
		DelayOutput : REAL; (*Data for internal use.*)
		DelayInput : REAL; (*Data for internal use.*)
		DelayTimeInternal : MTTempTimeDelayInternalType; (*Data for internal use.*)
		SetTempOld : REAL; (*Data for internal use.*)
		FeedForwardHeatOld : REAL; (*Data for internal use.*)
		FeedForwardHeatCheck : REAL; (*Data for internal use.*)
		HeatOutOld : REAL; (*Data for internal use.*)
		SetDerivative : LREAL; (*Data for internal use.*)
		PlantHeatingType : MTTempPlantEnum; (*Data for internal use.*)
		PlantCoolingType : MTTempPlantEnum; (*Data for internal use.*)
		AmbientTemperature : REAL; (*Data for internal use.*)
		DenyJump : BOOL; (*Data for internal use.*)
		KalmanFilter : MTTempKalmanType; (*Data for internal use.*)
	END_STRUCT;
	MTTempKalmanType : 	STRUCT  (*KalmanType.*)
		StatesFactor : ARRAY[0..2]OF LREAL;
		DynamicFactor : LREAL;
		ErrorCovariance : ARRAY[0..2,0..2]OF LREAL;
		SystemStates : ARRAY[0..2]OF LREAL;
		OutputVector : ARRAY[0..2]OF LREAL;
		InputVector : ARRAY[0..2]OF LREAL;
		SystemMatrix : ARRAY[0..2,0..2]OF LREAL;
	END_STRUCT;
	MTTempControllerLimitsType : 	STRUCT  (*Controller limits type.*)
		Counter : INT; (*Data for internal use.*)
		MaxHeatOutSent : BOOL; (*Data for internal use.*)
		HandshakeComplete : BOOL; (*Data for internal use.*)
		MaxCoolOutDone : BOOL; (*Data for internal use.*)
		FeedForwardStationary : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempDelayTimeType : 	STRUCT  (*Data for internal use.*)
		DelayTimeApproximation : REAL; (*Data for internal use.*)
		DelayTime : REAL; (*Data for internal use.*)
		NrAdjustArray : USINT; (*Data for internal use.*)
		ActualTaperFactor : INT; (*Data for internal use.*)
		TotalTaperFactor : INT; (*Data for internal use.*)
		TemperatureSampleTime : REAL; (*Data for internal use.*)
		ArrayCounter : USINT; (*Data for internal use.*)
		TemperatureArray : ARRAY[0..199]OF REAL; (*Data for internal use.*)
		Samples : INT; (*Data for internal use.*)
		SumTemperature : REAL; (*Data for internal use.*)
		SumActuatingVariable : REAL; (*Data for internal use.*)
		Warning : BOOL; (*Data for internal use.*)
		Error : BOOL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTempPIDType : 	STRUCT  (*PID controller type.*)
		MaxOut : REAL; (*Data for internal use.*)
		MinOut : REAL; (*Data for internal use.*)
		IntegrationPartPresetValue : REAL; (*Data for internal use.*)
		SetIntegrationPart : BOOL; (*Data for internal use.*)
		Parameters : MTPIDParametersType; (*Data for internal use.*)
		ControlError : REAL; (*Data for internal use.*)
		ControlErrorOld : REAL; (*Data for internal use.*)
		HoldIntegration : MTPIDIntegrationEnum; (*Data for internal use.*)
		ProportionalPart : REAL; (*Data for internal use.*)
		IntegrationPart : REAL; (*Data for internal use.*)
		DerivativePart : REAL; (*Data for internal use.*)
		Out : REAL; (*Data for internal use.*)
		IntegrationStatus : MTPIDIntegrationEnum; (*Data for internal use.*)
		DerivativeError : REAL; (*Data for internal use.*)
		StatusID : DINT; (*Data for internal use.*)
		OutOld : REAL; (*Data for internal use.*)
		GainOld : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempModeEnum : 
		( (*Enum to specify whether only heating or cooling is possible or both together.*)
		mtTMP_NO_TUNING := 0, (*No tuning.*)
		mtTMP_HEATING := 1, (*Heat tuning.*)
		mtTMP_COOLING := 2, (*Cool tuning.*)
		mtTMP_HEATING_COOLING := 3 (*Heat and cool tuning.*)
		);
END_TYPE

(*Types of MTTempSimulationModel*)

TYPE
	MTTempSimulationModelIntType : 	STRUCT  (*Internal parameter of function block MTTempSimulation.*)
		CycleTime : REAL; (*Task cycle time. Unit [s].*)
		ParametersValid : BOOL; (*Data for internal use.*)
		InhibitUpdate : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		Parameters : MTTempSimulationModelType; (*Data for internal use.*)
		NumberOfZones : USINT; (*Data for internal use.*)
		DelayTimeCoolOut : ARRAY[0..9]OF REAL; (*Data for internal use.*)
		DelayTimeHeatOut : ARRAY[0..9]OF REAL; (*Data for internal use.*)
		DelayTimeCool : {REDUND_UNREPLICABLE} ARRAY[0..9]OF MTTempTimeDelayInternalType; (*Data for internal use.*)
		DelayTimeHeat : {REDUND_UNREPLICABLE} ARRAY[0..9]OF MTTempTimeDelayInternalType; (*Data for internal use.*)
		ODEParameter : ARRAY[0..9]OF MTTempSimulationModelODEType; (*Data for internal use.*)
	END_STRUCT;
	MTTempSimulationModelODEType : 	STRUCT  (*Structure which contains all necassary information to solve the ODE of the temperature model.*)
		PHeat : ARRAY[0..2]OF REAL; (*Calculated PHeat values.*)
		PCool : ARRAY[0..2]OF REAL; (*Calculated PCool values.*)
		theta : ARRAY[0..2]OF REAL; (*Calculated theta values.*)
		thetaMat : ARRAY[0..2]OF REAL; (*Calculated theat material values.*)
		ZoneParameter : MTTempSimulationModelZoneType; (*Zone parameter for integration algorithm.*)
	END_STRUCT;
	MTTempSimulationModelType : 	STRUCT  (*Simulation parameters and nois.*)
		PlantParameters : ARRAY[0..9]OF MTTempPlantType; (*Plant parameters for heating and cooling.*)
		Noise : BOOL; (*Noise is activated or deactivated.*)
	END_STRUCT;
	MTTempSimulationModelZoneType : 	STRUCT  (*Parameters which are different for each zone.*)
		MaximumCoolingPower : REAL; (*Maximum cooling power.*)
		TimeConstantHeat : REAL; (*Time constant for heating.*)
		TimeConstantCool : REAL; (*Time constant for cooling.*)
		alphaXAmb : REAL; (*Specific heat coefficient between the zone of the extruder barrel and the ambience (air) . Unit [W/m²/K].*)
		ThermalCapacityExtruder : REAL; (*Thermal capacity of the extruder barrel. Unit [J/K].*)
	END_STRUCT;
END_TYPE

(*Types of MTTempTuning*)

TYPE
	MTTempTuningInternalType : 	STRUCT  (*Internal parameter of function block MTTempTuning.*)
		CycleTime : LREAL; (*Task cycle time. Unit [s].*)
		QualityChange : BOOL; (*Data for internal use.*)
		ParabelCase : BOOL; (*Data for internal use.*)
		ForceParabel : BOOL; (*Data for internal use.*)
		Master : BOOL; (*Data for internal use.*)
		MultiZone : BOOL; (*Data for internal use.*)
		CommunicationIn : MTTempCommunicationType; (*Data for internal use.*)
		CommunicationOut : MTTempCommunicationType; (*Data for internal use.*)
		SystemCheck : MTTempSystemCheckType; (*Data for internal use.*)
		IntegralFilter : MTTempIntegralFilterType; (*Data for internal use.*)
		DelayTime : MTTempDelayTimeType; (*Data for internal use.*)
		ControllerLimits : MTTempControllerLimitsType; (*Data for internal use.*)
		IdentIT1 : MTTempIdentificationType; (*Data for internal use.*)
		IdentPT2 : MTTempIdentificationType; (*Data for internal use.*)
		Prediction : MTTempPredictionType; (*Data for internal use.*)
		Switching : MTTempSwitchingType; (*Data for internal use.*)
		DisturbanceController : MTTempControllerType; (*Data for internal use.*)
		SetPointStabilityCheck : MTTempSetPointStabilityCheckType; (*Data for internal use.*)
		SetPointChange : MTTempSetPointChangeType; (*Data for internal use.*)
		ModelQuality : MTTempModelQualityType; (*Data for internal use.*)
		PlantParameters : MTTempPlantInternalType; (*Data for internal use.*)
		ActualPlantParameters : MTTempPlantParaInternalType; (*Data for internal use.*)
		Mode : MTTempTuningModeEnum; (*Data for internal use.*)
		IdentHeatRingBuffer : {REDUND_UNREPLICABLE} MTTempTimeDelayInternalType; (*Data for internal use.*)
		IdentCoolRingBuffer : {REDUND_UNREPLICABLE} MTTempTimeDelayInternalType; (*Data for internal use.*)
		ModelFirstPhase : USINT; (*Data for internal use.*)
		Model : USINT; (*Data for internal use.*)
		Time : REAL; (*Data for internal use.*)
		StartTime : REAL; (*Data for internal use.*)
		MaxFeedForwardHeat : REAL; (*Data for internal use.*)
		MaxFeedForwardCool : REAL; (*Data for internal use.*)
		HeatRingBufferOut : REAL; (*Data for internal use.*)
		CoolRingBufferOut : REAL; (*Data for internal use.*)
		TuningMode : USINT; (*Data for internal use.*)
		TuningDone : BOOL; (*Data for internal use.*)
		StartSingleZoneOld : BOOL; (*Data for internal use.*)
		StartMultiZoneOld : BOOL; (*Data for internal use.*)
		AmbientTemperature : REAL; (*Data for internal use.*)
		TemperatureOffset : REAL; (*Data for internal use.*)
		ActuatingVariableOffset : REAL; (*Data for internal use.*)
		NewTuning : BOOL; (*Data for internal use.*)
		ExpectedPT2Gain : REAL; (*Data for internal use.*)
		SetTemperature : REAL; (*Data for internal use.*)
		SetTemperatureOld : REAL; (*Data for internal use.*)
		SetPointTemperature : REAL; (*Data for internal use.*)
		SetPointTemperatureOK : BOOL; (*Data for internal use.*)
		TemperatureDiff : REAL; (*Data for internal use.*)
		TemperatureChange : REAL; (*Data for internal use.*)
		TemperatureChangeOld : REAL; (*Data for internal use.*)
		InitTemperatureCool : REAL; (*Data for internal use.*)
		CoolDownTemperature : REAL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		MaxHeatTrajectory : REAL; (*Data for internal use.*)
		State : USINT; (*Data for internal use.*)
		StateOld : USINT; (*Data for internal use.*)
		AbortOld : BOOL; (*Data for internal use.*)
		EnableParametersValid : BOOL; (*Data for internal use.*)
		LastValidPIDParameters : MTPIDParametersType; (*Data for internal use.*)
		LastValidPlantParameters : MTTempPlantParametersType; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		ParabelParameters : MTTempParabelType; (*Data for internal use.*)
		ProfileParameters : MTTempProfileType; (*Data for internal use.*)
	END_STRUCT;
	MTTempIdentificationType : 	STRUCT  (*Data for internal use.*)
		ParameterVector : ARRAY[0..2]OF LREAL; (*Data for internal use.*)
		UpdateMatrix : ARRAY[0..8]OF LREAL; (*Data for internal use.*)
		EstimationError : REAL; (*Data for internal use.*)
		WeightingFactor : REAL; (*Data for internal use.*)
		Samples : UINT; (*Data for internal use.*)
		IdentificationValid : BOOL; (*Data for internal use.*)
		Warning : BOOL; (*Data for internal use.*)
		Stop : BOOL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTempSetPointStabilityCheckType : 	STRUCT  (*Set point stability check type.*)
		SettlingIndex : UDINT; (*Data for internal use.*)
		MaxSettlingIndex : UDINT; (*Data for internal use.*)
		SettlingTime : REAL; (*Date for internal use.*)
		NumberOfSettlingPhases : USINT; (*Data for internal use.*)
		LQUpdateMatrix : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		LQOutput : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		Noise : REAL; (*Data for internal use.*)
		Error : BOOL; (*Data for internal use.*)
		Warning : BOOL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTempSetPointChangeType : 	STRUCT  (*Set point change type.*)
		SetPointChangeValid : BOOL; (*Data for internal use.*)
		WithinTemperatureBand : BOOL; (*Data for internal use.*)
		TimeForTemperatureCheck : REAL; (*Data for internal use.*)
		ActuatingVariableArray : ARRAY[0..9]OF REAL; (*Data for internal use.*)
		Warning : BOOL; (*Data for internal use.*)
		Error : BOOL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTempIntegralFilterType : 	STRUCT  (*Data for internal use.*)
		y : LREAL; (*Data for internal use.*)
		yI : LREAL; (*Data for internal use.*)
		yII : LREAL; (*Data for internal use.*)
		u : LREAL; (*Data for internal use.*)
		uI : LREAL; (*Data for internal use.*)
		uII : LREAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempModelQualityType : 	STRUCT  (*Model Quality Type.*)
		TimeArray : ARRAY[0..99]OF REAL; (*Data for internal use.*)
		TemperatureArray : ARRAY[0..99]OF REAL; (*Data for internal use.*)
		IT1TemperatureArray : ARRAY[0..99]OF REAL; (*Data for internal use.*)
		PT2TemperatureArray : ARRAY[0..99]OF REAL; (*Data for internal use.*)
		ArrayCounter : USINT; (*Data for internal use.*)
		DeltaTemperature : REAL; (*Data for internal use.*)
		HalfTemperature : REAL; (*Data for internal use.*)
		IT1MaxGain : REAL; (*Data for internal use.*)
		IT1MaxTimeConstant : REAL; (*Data for internal use.*)
		IT1MaxTime : REAL; (*Data for internal use.*)
		IT1MaxTemperature : REAL; (*Data for internal use.*)
		PT2MaxCurvature : REAL; (*Data for internal use.*)
		PT2MaxProduct : REAL; (*Data for internal use.*)
		PT2TimeOfPOI : REAL; (*Data for internal use.*)
		IT1SumSquareError : REAL; (*Data for internal use.*)
		PT2SumSquareError : REAL; (*Data for internal use.*)
		State : USINT; (*Data for internal use.*)
		EndTime : REAL; (*Data for internal use.*)
		EndTemperature : REAL; (*Data for internal use.*)
		SlopeOfLastValues : REAL; (*Data for internal use.*)
		ComplexPT2 : BOOL; (*Data for internal use.*)
		CounterCheck : DINT;
		ActTemptPOI : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempPredictionType : 	STRUCT  (*Prediction Type.*)
		t1 : REAL; (*Data for internal use.*)
		t2 : REAL; (*Data for internal use.*)
		FeedForwardStationary : REAL; (*Data for internal use.*)
		InitTemperature : REAL; (*Data for internal use.*)
		InitTime : REAL; (*Data for internal use.*)
		CalcInitParameter : BOOL; (*Data for internal use.*)
		Warning : BOOL; (*Data for internal use.*)
		Error : BOOL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTempSystemCheckType : 	STRUCT  (*System Check Type.*)
		SettlingIndex : UDINT; (*Data for internal use.*)
		MaxSettlingIndex : UDINT; (*Data for internal use.*)
		NumberOfSettlingPhases : USINT; (*Data for internal use.*)
		LQUpdateMatrix : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		LQOutput : ARRAY[0..1]OF REAL; (*Data for internal use.*)
		Noise : REAL; (*Data for internal use.*)
		Error : BOOL; (*Data for internal use.*)
		Warning : BOOL; (*Data for internal use.*)
		StartTemperature : REAL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
		Samples : UDINT; (*Data for internal use.*)
		SumTemperature : REAL; (*Data for internal use.*)
		SumActuatingVariable : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempSwitchingType : 	STRUCT  (*Switching Type.*)
		Warning : BOOL; (*Data for internal use.*)
		Error : BOOL; (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTempParabelType : 	STRUCT  (*Parabel Type.*)
		Temperature : REAL; (*Data for internal use.*)
		Time : REAL; (*Data for internal use.*)
		Slope : REAL; (*Data for internal use.*)
		ParabelCoefficient : REAL; (*Data for internal use.*)
		ParabelTimeMultiplicator : REAL; (*Data for internal use.*)
		ParabelEndTime : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempTuningModeEnum : 
		( (*Enum to specify whether only heating or cooling is possible or both together.*)
		mtTMP_HEAT_TUNING := 0, (*Heat tuning.*)
		mtTMP_COOL_TUNING := 1, (*Cool tuning.*)
		mtTMP_HEAT_COOL_TUNING := 2 (*Heat and cool tuning.*)
		);
	MTTempTuningStateEnum : 
		( (*Enum to specify the current tuning state.*)
		mtTMP_IDLE_STATE := 0, (*System waits for input commands.*)
		mtTMP_INIT_STATE := 1, (*Initial state for MultizoneTuning.*)
		mtTMP_SYSTEM_CHECK := 2, (*System is checked for stable operating point.*)
		mtTMP_IDENT_DELAY_TIME := 3, (*The time delay of the system is identified.*)
		mtTMP_IDENT_PARAMETERS := 4, (*The PID and plant parameters of the system are identified.*)
		mtTMP_PREDICTION := 5, (*Calculates the time for switching the actuating signal.*)
		mtTMP_SWITCH_SETPOINT := 6, (*System switches between two SetPoints.*)
		mtTMP_IN_SETPOINT := 7, (*System is in SetPoint and waits for further input.*)
		mtTMP_ERROR_STATE := 8, (*An error occured.*)
		mtTMP_TUNING_ABORTED_BY_USER
		);
END_TYPE

(*Types of MTTempProfile*)

TYPE
	MTTempProfileInternalType : 	STRUCT  (*Internal parameter of function block MTTempProfile.*)
		FeedForwardCoolDelayed : REAL; (*Data for internal use.*)
		FeedForwardHeatDelayed : REAL; (*Data for internal use.*)
		FeedForwardCool : REAL; (*Data for internal use.*)
		FeedForwardHeat : REAL; (*Data for internal use.*)
		CycleTime : LREAL; (*Task cycle time. Unit [s]*)
		EnableParametersValid : BOOL; (*Data for internal use.*)
		UpdateParametersValid : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		PlantParameters : MTTempPlantInternalType; (*Data for internal use.*)
		MaxHeatOut : REAL; (*Data for internal use.*)
		MaxCoolOut : REAL; (*Data for internal use.*)
		Mode : MTTempProfileModeEnum; (*Data for internal use.*)
		AmbientTemperature : REAL; (*Data for internal use.*)
		PossibleOperatingMode : MTTempSetPointChangeEnum; (*Data for internal use.*)
		InitTemperature : REAL; (*Data for internal use.*)
		InitOld : BOOL; (*Data for internal use.*)
		AbortOld : BOOL; (*Data for internal use.*)
		StartOld : BOOL; (*Data for internal use.*)
		MinFilterTime : REAL; (*Data for internal use.*)
		MinDelayTime : REAL; (*Data for internal use.*)
		MaxSlewRateGeneral : REAL; (*Data for internal use.*)
		MaxSlewRateConst : REAL; (*Data for internal use.*)
		StateOld : USINT; (*Data for internal use.*)
		State : USINT; (*Data for internal use.*)
		ProfileData : MTTempProfileDataType; (*Data for internal use.*)
		InitDone : BOOL; (*Data for internal use.*)
		InSetPointEdge : BOOL; (*Data for internal use.*)
		InSetPointOld : BOOL; (*Data for internal use.*)
		InSetPoint : BOOL; (*Data for internal use.*)
		SetTemperature : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		SetTemperatureDelayed : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		ProfileDataValid : BOOL; (*Data for internal use.*)
		IT1Type : MTTemProfileIT1Type; (*Data for internal use.*)
		StatusIDCommando : DINT; (*Data for internal use.*)
		StatusIDUpdate : DINT; (*Data for internal use.*)
		FilterTimeMissing : BOOL; (*Data for internal use.*)
		PlantParametersMissing : BOOL; (*Data for internal use.*)
		SlewRateMissing : BOOL; (*Data for internal use.*)
		TimeOptimizedParameters : MTTempProfileTimeOptimizedType; (*Data for internal use.*)
		SlewSystem : REAL; (*Data for internal use.*)
		SlewConst : REAL; (*Data for internal use.*)
		ProfileParameters : MTTempProfileType; (*Data for internal use.*)
	END_STRUCT;
	MTTempProfileTimeOptimizedType : 	STRUCT  (*Time optimized Type.*)
		DeltaAmbient : REAL; (*Data for internal use.*)
		DeltaAmbientStart : REAL; (*Data for internal use.*)
		DeltaChange : REAL; (*Data for internal use.*)
		SwitchingTime1 : REAL; (*Data for internal use.*)
		SwitchingTime2 : REAL; (*Data for internal use.*)
		FeedForwardStationary : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTemProfileIT1Type : 	STRUCT  (*IT1 Type.*)
		a0 : LREAL; (*Data for internal use.*)
		a1 : LREAL; (*Data for internal use.*)
		b0 : LREAL; (*Data for internal use.*)
		b1 : LREAL; (*Data for internal use.*)
		y : ARRAY[0..2]OF LREAL; (*Data for internal use.*)
		u : ARRAY[0..2]OF LREAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempProfileDataType : 	STRUCT  (*Profile Data Type.*)
		SetTemperatureStart : REAL; (*Inital temperature at output SetTemperature before Start command. Can be InitTemperature, AmbientTemperature or last SetPointTemperature.*)
		SetPointTemperature : REAL; (*Data for internal use.*)
		SlewRate : REAL; (*Data for internal use.*)
		FilterTime : REAL; (*Data for internal use.*)
		DelayTime : REAL; (*Data for internal use.*)
		ActualOperatingMode : MTTempSetPointChangeEnum; (*Data for internal use.*)
		MinSetPointTemperature : REAL; (*Data for internal use.*)
		MaxSetPointTemperature : REAL; (*Data for internal use.*)
		EndtimeOfConstantDerivative : REAL; (*Data for internal use.*)
		TimeDelayedFF : REAL; (*Data for internal use.*)
		TimeDelayed : REAL; (*Data for internal use.*)
		HeatAreaFF : LREAL; (*Remaining HeatArea to reach setpoint for FeedForward.*)
		HeatArea : LREAL; (*Remaining HeatArea to reach setpoint for SetPointTemperature.*)
		HeatAreaSaturation : LREAL; (*HeatArea above MaxHeatOut.*)
		TimeLong : LREAL; (*Data for internal use.*)
		Time : REAL; (*Data for internal use.*)
		PlantCoolTimeDelay : REAL; (*Data for internal use.*)
		PlantHeatTimeDelay : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTTempSetPointChangeEnum : 
		( (*Enum to specify whether only heating or cooling is possible or both together.*)
		mtTMP_NO_CHANGE := 0, (*No set point change possible.*)
		mtTMP_POSITIVE_CHANGE := 1, (*Only positive set point change possible.*)
		mtTMP_NEGATIVE_CHANGE := 2, (*Only negative set point change possible.*)
		mtTMP_POS_NEG_CHANGE := 3 (*All set point changes possible.*)
		);
	MTTempProfileModeEnum : 
		( (*Enum to specify the mode of the profile generation.*)
		mtTMP_TIME_OPTIMIZED_PROFILE := 0, (*SetTemperature is a time optimized profile.*)
		mtTMP_RATE_LIMITED_PROFILE := 1 (*SetTemperature is a user defined rate limited profile.*)
		);
	MTTempProfileStateEnum : 
		( (*Enum to specify the current state of the function block.*)
		mtTMP_PROFILE_DISABLED := 0, (*Function block not active.*)
		mtTMP_PROFILE_READY := 1, (*System waits for input commands.*)
		mtTMP_PROFILE_IN_MOTION := 2, (*System outputs generated temperature profile.*)
		mtTMP_PROFILE_ABORTED_BY_USER := 3 (*Profile output was aborted by user.*)
		);
END_TYPE
