
TYPE
	MTTensionParametersType : 	STRUCT  (*Decoupling parameters.*)
		NumberOfZones : USINT; (*Number of zones.*)
		WebLength : ARRAY[0..19]OF DINT; (*L[i] denotes the free web length between FR#i and FR#i+1.*)
	END_STRUCT;
	MTTensionSimulationType : 	STRUCT  (*Simulation parameters.*)
		WebFactor : REAL; (*WebFactor EA.*)
		NumberOfZones : USINT; (*Number of zones.*)
		WebLength : ARRAY[0..19]OF DINT; (*L[i] denotes the free web length between FR#i and FR#i+1.*)
		Noise : BOOL; (*Noise on/off.*)
	END_STRUCT;
	MTTensionControllerInternalType : 	STRUCT  (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParametersValid : BOOL; (*Data for internal use.*)
		WebFactor : REAL; (*Data for internal use.*)
		WebLength : REAL; (*Data for internal use.*)
		MaxVelocityCorrection : REAL; (*Data for internal use.*)
		ResponseRate : REAL; (*Data for internal use.*)
		ResponseOvershoot : REAL; (*Data for internal use.*)
		PrefilterOut : REAL; (*Data for internal use.*)
		ProportionalPart : REAL; (*Data for internal use.*)
		IntegrationPart : REAL; (*Data for internal use.*)
		TensionErrorOld : REAL; (*Data for internal use.*)
		TensionError : REAL; (*Data for internal use.*)
		DerivativePart : REAL; (*Data for internal use.*)
		ControlParameters : MTPIDParametersType; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		InitController : BOOL; (*Data for internal use.*)
		InitControllerOld : BOOL; (*Data for internal use.*)
		UpdateParametersValid : BOOL; (*Data for internal use.*)
		InitParametersValid : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		IntegrationStatus : MTPIDIntegrationEnum; (*Data for internal use.*)
		PID_StatusID : DINT; (*Data for internal use.*)
	END_STRUCT;
	MTTensionDecouplingInternalType : 	STRUCT  (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParametersValid : BOOL; (*Data for internal use.*)
		Parameters : MTTensionParametersType; (*Data for internal use.*)
		Strain : ARRAY[0..19]OF LREAL; (*Data for internal use.*)
		SetLineVelocityOld : REAL; (*Data for internal use.*)
		ActLineAcceleration : REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTTensionSimulationModelIntType : 	STRUCT  (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParametersValid : BOOL; (*Data for internal use.*)
		Parameters : MTTensionSimulationType; (*Data for internal use.*)
		Strain : ARRAY[0..19]OF LREAL; (*Data for internal use.*)
		MaterialBreak : ARRAY[0..19]OF BOOL; (*Data for internal use.*)
		RestOfMaterial : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		Update : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
	END_STRUCT;
END_TYPE
