
TYPE
	MTRegisterControllerInternalType : 	STRUCT  (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ImageLength : REAL; (*Data for internal use.*)
		WebLength : REAL; (*Data for internal use.*)
		SensorPosition : REAL; (*Data for internal use.*)
		MaxVelocityCorrection : REAL; (*Data for internal use.*)
		ResponseRate : REAL; (*Data for internal use.*)
		ResponseOvershoot : REAL; (*Data for internal use.*)
		PrefilterOut : REAL; (*Data for internal use.*)
		ControlStateVariable : REAL; (*Data for internal use.*)
		ControllerParameter : ARRAY[0..2]OF REAL; (*Data for internal use.*)
		ActSystemSampleTime : REAL; (*Data for internal use.*)
		UpdateParametersValid : BOOL; (*Data for internal use.*)
		InitParametersValid : BOOL; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		InitControllerOld : BOOL; (*Data for internal use.*)
		TriggerOld : BOOL; (*Data for internal use.*)
		ResetOld : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTRegisterControlModeEnum : 
		( (*Mode for the longitudinal register error.*)
		mtPRN_KEY_COLOR := 0, (*Key color mode.*)
		mtPRN_SEQUENTIAL_COLOR := 1 (*Sequential color mode.*)
		);
	MTRegisterDecouplingInternalType : 	STRUCT  (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParametersValid : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : {REDUND_UNREPLICABLE} BOOL; (*Data for internal use.*)
		Parameters : {REDUND_UNREPLICABLE} MTRegisterSystemType; (*Data for internal use.*)
		Strain : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		DelayedStrain : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		DelayedChangingStrain : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		NumberOfBufferElements : UINT; (*Data for internal use.*)
		UpdateEpsBuffer : ARRAY[0..18]OF BOOL; (*Data for internal use.*)
		UpdateEpsDerBuffer : ARRAY[0..18]OF BOOL; (*Data for internal use.*)
		EpsBuffer : ARRAY[0..18]OF MTRegisterTransDelayBufferType; (*Data for internal use.*)
		EpsDerBuffer : ARRAY[0..18]OF MTRegisterTransDelayBufferType; (*Data for internal use.*)
		TransportDelayDerivation : ARRAY[0..18]OF REAL; (*Data for internal use.*)
	END_STRUCT;
	MTRegisterSimulationModelIntType : 	STRUCT  (*Data for internal use.*)
		CycleTime : REAL; (*Task cycle time. Unit: [s].*)
		ParametersValid : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : {REDUND_UNREPLICABLE} BOOL; (*Data for internal use.*)
		Parameters : {REDUND_UNREPLICABLE} MTRegisterSimulationModelType; (*Data for internal use.*)
		Strain : ARRAY[0..19]OF LREAL; (*Data for internal use.*)
		DelayedStrain : ARRAY[0..19]OF LREAL; (*Data for internal use.*)
		KeyError : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		SequentialError : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		MaterialBreak : ARRAY[0..19]OF BOOL; (*Data for internal use.*)
		RestOfMaterial : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		RegisterError : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		DeltaPos : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		Trigger : ARRAY[0..19]OF BOOL; (*Data for internal use.*)
		NumberEpsBufferElements : USINT; (*Data for internal use.*)
		UpdateEpsBuffer : ARRAY[0..18]OF BOOL; (*Data for internal use.*)
		EpsBuffer : ARRAY[0..18]OF MTRegisterTransDelayLRBufferType; (*Data for internal use.*)
	END_STRUCT;
	MTRegisterSimulationModelType : 	STRUCT  (*Parameter for the simulation model.*)
		NumberOfPrintingUnits : USINT; (*Number of printing units.*)
		ImageLength : DINT; (*Circumference of printing cylinders.*)
		WebLength : ARRAY[0..19]OF DINT; (*Web length between PU#i and PU#i-1. Unit: [µm].*)
		SensorPosition : ARRAY[0..19]OF DINT; (*Distance from printing unit to register mark sensor LSi. Unit: [µm].*)
		Mode : ARRAY[0..19]OF MTRegisterControlModeEnum; (*Control mode array.*)
		TensionIn : REAL; (*Feed tension prior to the first printing unit. Unit: [N].*)
		Noise : BOOL; (*Measurement noise is enabled or disabled.*)
	END_STRUCT;
	MTRegisterSystemType : 	STRUCT  (*System parameters for the decoupling.*)
		NumberOfPrintingUnits : USINT; (*Number of printing units. *)
		WebLength : ARRAY[0..19]OF DINT; (*Web length between PU#i und PU#i-1. Unit: [µm].*)
		Mode : ARRAY[0..19]OF MTRegisterControlModeEnum; (*Control mode array.*)
		AccelerationCompensation : BOOL; (*Compensation of additional acceleration terms.*)
	END_STRUCT;
	MTRegisterTransDelayBufferType : 	STRUCT  (*Buffer parameters for the transport delay.*)
		NumberOfBufferElements : UDINT; (*Data for internal use.*)
		CurrentIndex : UDINT; (*Data for internal use.*)
		DelayIndex : UDINT; (*Data for internal use.*)
		DiffIndex : DINT; (*Data for internal use.*)
		Integration : LREAL; (*Data for internal use.*)
		DataIn : REFERENCE TO REAL; (*Data for internal use.*)
		DataTt : REFERENCE TO REAL; (*Data for internal use.*)
		TimeDelay : REAL; (*Data for internal use.*)
		TransportDelay : REAL; (*Data for internal use.*)
		TransportDelayDerivation : REAL; (*Data for internal use.*)
		MaxDelayTime : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTRegisterTransDelayLRBufferType : 	STRUCT  (*Buffer parameters for the transport delay.*)
		NumberOfBufferElements : UDINT; (*Data for internal use.*)
		CurrentIndex : UDINT; (*Data for internal use.*)
		DelayIndex : UDINT; (*Data for internal use.*)
		DiffIndex : DINT; (*Data for internal use.*)
		Integration : LREAL; (*Data for internal use.*)
		DataIn : REFERENCE TO LREAL; (*Data for internal use.*)
		DataTt : REFERENCE TO REAL; (*Data for internal use.*)
		TimeDelay : REAL; (*Data for internal use.*)
		TransportDelay : REAL; (*Data for internal use.*)
		TransportDelayDerivation : REAL; (*Data for internal use.*)
		MaxDelayTime : REAL; (*Data for internal use.*)
	END_STRUCT;
END_TYPE
