(*VelocityGenerator Types*)

TYPE
	MTHydGenVelGenInternalType : 	STRUCT  (*Structure of internal parameters.*)
		CycleTime : LREAL; (*Task cycle time. Unit: [s].*)
		InhibitUpdate : BOOL; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		Parameters : MTHydGenVelGenParType; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		TargetPoint : MTHydGenVelGenTargetPointType; (*Data for internal use.*)
		SafePoints : ARRAY[0..9]OF MTHydGenVelGenSafePointType; (*Data for internal use.*)
		StartOld : BOOL; (*Data for internal use.*)
		StopOld : BOOL; (*Data for internal use.*)
		AbortOld : BOOL; (*Data for internal use.*)
		SetInitVelocityOld : BOOL; (*Data for internal use.*)
		StoppingActive : BOOL; (*Data for internal use.*)
		vRef : LREAL; (*Data for internal use.*)
		moveDir : MTHydGenVelGenDirectionEnum; (*Data for internal use.*)
		aAcc : LREAL; (*Data for internal use.*)
		aDec : LREAL; (*Data for internal use.*)
		jAcc : LREAL; (*Data for internal use.*)
		jDec : LREAL; (*Data for internal use.*)
		ProfileState : USINT; (*Data for internal use.*)
		vSetProfileGen : LREAL; (*Data for internal use.*)
		aSetProfileGen : LREAL; (*Data for internal use.*)
		jSetProfileGen : LREAL; (*Data for internal use.*)
		vSetPBB : LREAL; (*Data for internal use.*)
		aSetPBB : LREAL; (*Data for internal use.*)
		jSetPBB : LREAL; (*Data for internal use.*)
		vPrev : LREAL; (*Data for internal use.*)
		aPrev : LREAL; (*Data for internal use.*)
		JoltCorrectionActive : BOOL; (*Data for internal use.*)
		vJoltProfileGen : LREAL; (*Data for internal use.*)
		ExecuteStartMovement : BOOL; (*Data for internal use.*)
		TP_PBB_Data : MTHydGenVelGenPBBDataType; (*Data for internal use.*)
		SP_PBB_Data : ARRAY[0..9]OF MTHydGenVelGenPBBDataType; (*Data for internal use.*)
		PBB_Temp : MTHydGenVelGenPBBDataType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenVelGenParType : 	STRUCT  (*Structure with parameters.*)
		PositiveDirection : MTHydGenVelGenParDirType; (*Parameters for positve movement.*)
		NegativeDirection : MTHydGenVelGenParDirType; (*Parameters for negative movement.*)
	END_STRUCT;
	MTHydGenVelGenTPInfoType : 	STRUCT  (*Structure with informations for the TargetPoint.*)
		ActDirection : MTHydGenVelGenDirectionEnum; (*This is the currently movement or was the last movement. TargetPoint informations are related to this direction. *)
		Enabled : BOOL; (*TargetPoint is enabled.*)
		Reached : BOOL; (*TargetPoint is reached.*)
		PositionBasedBrakingActive : BOOL; (*Position-based-braking to the target point is active.*)
		DistanceToStartBraking : REAL; (*Distance to start position-based-braking to the TargetPoint. Unit: [mm].*)
		ActDeceleration : REAL; (*This deceleration will be actual used for position-based-braking to the TargetPoint. Unit: [mm/s^2]*)
		ActDeadTime : REAL; (*This dead time will be actual used for position-based-braking to the TargetPoint. Unit: [s]*)
	END_STRUCT;
	MTHydGenVelGenTargetPointType : 	STRUCT  (*Structure with parameters for the TargetPoint.*)
		PositiveDirection : MTHydGenVelGenTargetPointDirType; (*Parameters for positve movement.*)
		NegativeDirection : MTHydGenVelGenTargetPointDirType; (*Parameters for negative movement.*)
	END_STRUCT;
	MTHydGenVelGenTargetPointDirType : 	STRUCT  (*Structure with parameters for a specified movement direction for the TargetPoint.*)
		Enable : BOOL; (*This flag has to be set if the movement should slow down to the "target point" before it reaches the target position. *)
		Position : REAL; (*Target position. Unit [mm]*)
		Velocity : REAL; (*Velocity at the target position. Unit: [mm/s]*)
		Deceleration : REAL; (*Deceleration for position-based-braking to the target point. Unit: [mm/s^2]*)
		DeadTime : REAL; (*Dead time for position-based-braking to the target point. Unit: [s]*)
		JoltTime : REAL; (*Jolt time for position based braking to the target point. If JoltTime=0, the value JoltTime defined in the structure Parameters is used. Unit: [s]*)
		EnableDecelerationCurve : BOOL; (*This flag has to be set if the Deceleration should be adjusted by a table. Instead of the value Deceleration the curve (a velocity depending curve) defined in DecelerationTable will be used.*)
		DecelerationTable : MTHydGenVelGenDecTableType; (*Structure for a velocity depending deceleration. This has only an effect if EnableDecelerationCurve=True.*)
		EnableDeadTimeCurve : BOOL; (*This flag has to be set if the DeadTime should be adjusted by a table. Instead of the value DeadTime the curve (a velocity depending curve) defined in DeadTimeTable will be used.*)
		DeadTimeTable : MTHydGenVelGenDeadTimeTableType; (*Structure for a velocity depending dead time. This has only an effect if EnableDeadTimeCurve=True.*)
	END_STRUCT;
	MTHydGenVelGenSPInfoType : 	STRUCT  (*Structure with informations for the SafePoints.*)
		ActDirection : MTHydGenVelGenDirectionEnum; (*This is the currently movement or was the last movement. SafePoint informations are related to this direction. *)
		Enabled : BOOL; (*SafePoint is enabled.*)
		Reached : BOOL; (*SafePoint is reached.*)
		PositionBasedBrakingActive : BOOL; (*Position-based-braking to the safe point is active.*)
		DistanceToStartBraking : REAL; (*Distance to start position-based-braking to the corresponding SafePoint. Unit: [mm].*)
	END_STRUCT;
	MTHydGenVelGenSafePointType : 	STRUCT  (*Structure with parameters for the SafePoint*)
		PositiveDirection : MTHydGenVelGenSafePointDirType; (*Parameters for positve movement.*)
		NegativeDirection : MTHydGenVelGenSafePointDirType; (*Parameters for negative movement.*)
	END_STRUCT;
	MTHydGenVelGenSafePointDirType : 	STRUCT  (*Structure with parameters for a specified movement direction for the SafePoint.*)
		Enable : BOOL; (*This flag has to be set if the movement should slow down to the "safe point" before it reaches the safe position.*)
		Position : REAL; (*Safe position. Unit: [mm]*)
		Velocity : REAL; (*Velocity at safe position. Unit: [mm/s]*)
		Deceleration : REAL; (*Deceleration for position-based-braking to the safe point. Unit: [mm/s^2]*)
		DeadTime : REAL; (*Dead time for position-based-braking to the safe point. Unit: [s]*)
		JoltTime : REAL; (*Jolt time for position-based-braking to the safe point. If JoltTime=0, the value JoltTime defined in the structure Parameters is used. Unit: [s]*)
	END_STRUCT;
	MTHydGenVelGenPBBDataType : 	STRUCT  (*Internal structure for PBB*)
		CycleTime : LREAL; (*cycle time*)
		Enabled : BOOL; (*Is PBB enabled*)
		sTarget : LREAL; (*Target position [mm]*)
		vTarget : LREAL; (*Target velocity [mm/s]*)
		aMax : LREAL; (*Maximum deceleration for PBB [mm/s^2] (signed).*)
		j0 : LREAL; (*Jerk in Phase0*)
		j1 : LREAL; (*Jerk in Phase1*)
		j3 : LREAL; (*Jerk in Phase3*)
		tDead : LREAL; (*dead time [s]*)
		Active : BOOL; (*Is PBB active*)
		Reached : BOOL; (*Is TargetPoint reached*)
		DistanceToStartBraking : LREAL; (*distance to start PBB (absolut value)*)
		Phase : USINT; (*PBB Phase*)
		sBrake : LREAL; (*braking distance [mm]*)
		s0s : LREAL; (*start position in phase0 [mm]*)
		v0s : LREAL; (*start velocity in phase0 [mm/s]*)
		a0s : LREAL; (*start acceleration in phase0 [mm/s^2]*)
		s1s : LREAL; (*start position in phase1 [mm]*)
		v1s : LREAL; (*start velocity in phase1 [mm/s]*)
		a1s : LREAL; (*start acceleration in phase1 [mm/s^2]*)
		s2s : LREAL; (*start position in phase2 [mm]*)
		v2s : LREAL; (*start velocity in phase2 [mm/s]*)
		s3s : LREAL; (*start position in phase3 [mm]*)
		v3s : LREAL; (*start velocity in phase3 [mm/s]*)
		delta_t0 : LREAL; (*braking time in phase0 [s]*)
		delta_s0 : LREAL; (*position difference in phase0 [mm]*)
		delta_v0 : LREAL; (*velocity difference in phase0 [mm/s]*)
		delta_t1 : LREAL; (*braking time in phase1 [s]*)
		delta_s1 : LREAL; (*position difference in phase1 [mm]*)
		delta_v1 : LREAL; (*velocity difference in phase1 [mm/s]*)
		delta_t2 : LREAL; (*braking time in phase2 [s]*)
		delta_s2 : LREAL; (*position difference in phase2 [mm]*)
		delta_v2 : LREAL; (*velocity difference in phase2 [mm/s]*)
		delta_t3 : LREAL; (*braking time in phase2 [s]*)
		delta_s3 : LREAL; (*position difference in phase3 [mm]*)
		delta_v3 : LREAL; (*velocity difference in phase3 [mm/s]*)
		PBA : BOOL; (*position based acceleration*)
		vRefLim : BOOL; (*Is a limitation of reference velocity is necessary*)
	END_STRUCT;
	MTHydGenVelGenParDirType : 	STRUCT  (*Structure with parameters for a specified movement direction.*)
		Acceleration : REAL; (*Acceleration of the profile. Unit: [mm/s^2]*)
		Deceleration : REAL; (*Deceleration of the profile. Unit: [mm/s^2]*)
		StopDeceleration : REAL; (*Deceleration for stopping. This value is used by a stop command. Unit: [mm/s^2]*)
		JoltTime : REAL; (*Jolt limitation time. Unit: [s]*)
	END_STRUCT;
	MTHydGenVelGenDecTableType : 	STRUCT  (*Structure with parameters for a velocity depending deceleration curve.*)
		Velocity : ARRAY[0..9]OF REAL; (*Velocity points for a velocity depending deceleration. Unit: [mm/s]*)
		Deceleration : ARRAY[0..9]OF REAL; (*Deceleration points for a velocity depending deceleration. Unit: [mm/s^2]. Valid value range: Deceleration > 0. *)
		NumberOfNodes : USINT; (*Number of nodes to define the velocity depending deceleration curve. Valid value range: 0 < NumberOfNodes <= 10 if EnableDecelerationCurve = True.*)
	END_STRUCT;
	MTHydGenVelGenDeadTimeTableType : 	STRUCT  (*Structure with parameters for a velocity depending dead time curve.*)
		Velocity : ARRAY[0..9]OF REAL; (*Velocity points for a velocity depending dead time. Unit: [mm/s]*)
		DeadTime : ARRAY[0..9]OF REAL; (*DeadTime points for a velocity depending dead time. Unit: [s]. *)
		NumberOfNodes : USINT; (*Number of nodes to define the velocity depending dead time curve. Valid value range: 0 < NumberOfNodes <= 10 if EnableDeadTimeCurve = True.*)
	END_STRUCT;
END_TYPE

(*Velocity Generator Enums*)

TYPE
	MTHydGenVelGenMovementStateEnum : 
		( (*Movement state enums*)
		mtHYDGEN_POS_DIR_STOPPING := 6, (*Stopping in positive direction is active.*)
		mtHYDGEN_POS_DIR_PBB_SAFEPOINT := 5, (*Position-Based-Braking to a SafePoint in positive direction is active.*)
		mtHYDGEN_POS_DIR_PBB_TARGETPOINT := 4, (*Position-Based-Braking to the TargetPoint in positive direction is active.*)
		mtHYDGEN_POS_DIR_DECELERATION := 3, (*Deceleration in positive direction.*)
		mtHYDGEN_POS_DIR_CONST_MOVEMENT := 2, (*Constant movement in positive direction.*)
		mtHYDGEN_POS_DIR_ACCELERATION := 1, (*Acceleration in positive direction.*)
		mtHYDGEN_STAND_STILL := 0, (*Stand still (no movement).*)
		mtHYDGEN_NEG_DIR_ACCELERATION := -1, (*Acceleration in negative direction.*)
		mtHYDGEN_NEG_DIR_CONST_MOVEMENT := -2, (*Constant movement in negative direction.*)
		mtHYDGEN_NEG_DIR_DECELERATION := -3, (*Deceleration in negative direction.*)
		mtHYDGEN_NEG_DIR_PBB_TARGETPOINT := -4, (*Position-Based-Braking to the TargetPoint in negative direction is active.*)
		mtHYDGEN_NEG_DIR_PBB_SAFEPOINT := -5, (*Position-Based-Braking to a SafePoint in negative direction is active.*)
		mtHYDGEN_NEG_DIR_STOPPING := -6 (*Stopping in negative direction is active.*)
		);
	MTHydGenVelGenDirectionEnum : 
		( (*Driving direction enums*)
		mtHYDGEN_POS_MOVEMENT := 1, (*Movement in positive direction.*)
		mtHYDGEN_NO_MOVEMENT := 0, (*No Movement.*)
		mtHYDGEN_NEG_MOVEMENT := -1 (*Movement in negative direction.*)
		);
END_TYPE

(*Profile Identification Types*)

TYPE
	MTHydGenProfileIdentParType : 	STRUCT  (*Identification parameters.*)
		PositiveDirection : MTHydGenProfileIdentParDirType; (*Parameters for positive movement direction.*)
		NegativeDirection : MTHydGenProfileIdentParDirType; (*Parameters for negative movement direction.*)
		MinAllowedCylinderPosition : REAL; (*Minmum allowed cylinder position Unit: [mm]. Valid value range: MinAllowedCylinderPosition < MaxAllowedCylinderPosition.*)
		MaxAllowedCylinderPosition : REAL; (*Maximum allowed cylinder position. Unit: [mm]. Valid value range: MaxAllowedCylinderPosition > MinAllowedCylinderPosition.*)
	END_STRUCT;
	MTHydGenProfileIdentParDirType : 	STRUCT  (*Identification parameters.*)
		TargetCylinderPosition : REAL; (*Target position. Unit: [mm]. Valid value range:MinAllowedCylinderPosition < NegativeDirection.TargetCylinderPosition < PositiveDirection.TargetCylinderPosition < MaxAllowedCylinderPosition.
*)
		MaxCylinderVelocity : REAL; (*Absolut value of maximum cylinder velocity. Unit: [mm/s]. Valid value range: MaxCylVelocity > 0.0.*)
		CylinderVelocityStep1 : REAL := 10; (*Step height of set cylinder velocity for the first identificaiton movement. Unit: [% of MaxCylinderVelocity]. Valid value range: 0.0 < CylinderVelocityStep1 <= 100.0.*)
		CylinderVelocityStep2 : REAL := 20; (*Step height of set cylinder velocity for the second identificaiton movement. Unit: [% of MaxCylinderVelocity]. Valid value range: 0.0 < CylinderVelocityStep2 <= 100.0.*)
		CylinderVelocityStep3 : REAL := 30; (*Step height of set cylinder velocity for the third identificaiton movement. Unit: [% of MaxCylinderVelocity]. Valid value range: 0.0 < CylinderVelocityStep3 <= 100.0.*)
	END_STRUCT;
	MTHydGenProfileIdentDeadTimeType : 	STRUCT  (*Identification parameters for dead time.*)
		PositiveDirection : MTHydGenProfIdentDeadTimeDirType; (*Dead time identification parameters for positive movement direction.*)
		NegativeDirection : MTHydGenProfIdentDeadTimeDirType; (*Dead time identification parameters for negative movement direction.*)
	END_STRUCT;
	MTHydGenProfIdentDeadTimeDirType : 	STRUCT  (*Identification parameters for dead time.*)
		Mode : MTHydGenProfileIdentDTModeEnum := mtHYDGEN_DEADTIME_IDENT_OFF; (*Mode for dead time identification.*)
		TuningVelocity : REAL; (*Absolute value of the cylinder velocity for tuning the dead time. Unit: [mm/s]*)
		UpperPositionTolerance : REAL := 0.5; (*Allowed upper limit for position deviation. Unit: [mm]*)
		LowerPositionTolerance : REAL := -0.2; (*Allowed lower limit for position deviation. Unit: [mm]*)
		TestValues : ARRAY[0..9]OF REAL := [0,0.001,0.005,0.01,0.025,0.05,0.075,0.1,0.125,0.15]; (*Values for dead time identification with Mode=mtHYDGEN_DEADTIME_IDENT_BASIC*)
		MinDeadTime : REAL := 0.0; (*Minimal allowed dead time for dead time identificaiton with Mode=mtHYDGEN_DEADTIME_IDENT_ADVANCED*)
		MaxDeadTime : REAL := 0.2; (*Maximal allowed dead time for dead time identificaiton with Mode=mtHYDGEN_DEADTIME_IDENT_ADVANCED*)
	END_STRUCT;
	MTHydGenProfileIdentOutputType : 	STRUCT  (*Identified parameters.*)
		PositiveDirection : MTHydGenProfIdentOutputDirType; (*Identified parameters in positive direction.*)
		NegativeDirection : MTHydGenProfIdentOutputDirType; (*Identified parameters in negative direction.*)
	END_STRUCT;
	MTHydGenProfIdentOutputDirType : 	STRUCT  (*Identified accelererations, decelerations and dead times.*)
		Acceleration : REAL; (*Identified acceleration. Unit: [mm/s²].*)
		Deceleration : REAL; (*Identified deceleration. Unit: [mm/s²].*)
		TargetDeceleration : REAL; (*Identified target deceleration. Unit: [mm/s²].*)
		DeadTime : REAL; (*Identified dead time. Unit: [s].*)
	END_STRUCT;
	MTHydGenProfieIdentQualityType : 	STRUCT  (*Quality of the identified parameters.*)
		PositiveDirection : MTHydGenProfIdentQualityDirType; (*Quality of the identified parameters in positive direction.*)
		NegativeDirection : MTHydGenProfIdentQualityDirType; (*Quality of the identified parameters in negative direction.*)
	END_STRUCT;
	MTHydGenProfIdentQualityDirType : 	STRUCT  (*Quality of identified accelerations, decelerations and dead times.*)
		Acceleration : REAL; (*Quality of identified acceleration. Unit: [%].*)
		Deceleration : REAL; (*Quality of identified deceleration. Unit: [%].*)
		TargetDeceleration : REAL; (*Quality of identified target deceleration. Unit: [%].*)
		DeadTime : REAL; (*Quality of identified dead time. Unit: [%].*)
	END_STRUCT;
	MTHydGenProfileIdentStatCalcType : 	STRUCT  (*Data for internal use.*)
		Inputs : ARRAY[0..2]OF LREAL; (*Data for internal use.*)
		Mean : LREAL; (*Data for internal use.*)
		Variance : LREAL; (*Data for internal use.*)
		StandardDeviation : LREAL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfileIdentStatDTType : 	STRUCT  (*Data for internal use.*)
		Value : REAL; (*Data for internal use.*)
		EndDeviation : REAL; (*Data for internal use.*)
		MaxDeviation : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfileIdentStatDirType : 	STRUCT  (*Data for internal use.*)
		DeadTime : ARRAY[0..9]OF MTHydGenProfileIdentStatDTType; (*Data for internal use.*)
		Acceleration : MTHydGenProfileIdentStatCalcType; (*Data for internal use.*)
		Deceleration : MTHydGenProfileIdentStatCalcType; (*Data for internal use.*)
		TargetDeceleration : MTHydGenProfileIdentStatCalcType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfileIdentStatType : 	STRUCT  (*Data for internal use.*)
		PosDir : MTHydGenProfileIdentStatDirType; (*Data for internal use.*)
		NegDir : MTHydGenProfileIdentStatDirType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfileIdentMoveAvgType : 	STRUCT  (*Data for internal use.*)
		NumOfElmements : USINT; (*Data for internal use.*)
		Buffer : ARRAY[0..19]OF REAL; (*Data for internal use.*)
		CntAct : USINT; (*Data for internal use.*)
		CntOld : USINT; (*Data for internal use.*)
		BufferFull : BOOL; (*Data for internal use.*)
		Sum : REAL; (*Data for internal use.*)
		Average : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentifiedParType : 	STRUCT  (*Data for internal use.*)
		PosDir : MTHydGenProfIdentifiedParDirType; (*Data for internal use.*)
		NegDir : MTHydGenProfIdentifiedParDirType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentifiedParDirType : 	STRUCT  (*Data for internal use.*)
		UnscaledAcc : LREAL; (*Data for internal use.*)
		UnscaledDec : LREAL; (*Data for internal use.*)
		UnscaledTargetDec : LREAL; (*Data for internal use.*)
		TimeConstant : LREAL; (*Data for internal use.*)
		ScaledAcc : LREAL; (*Data for internal use.*)
		ScaledDec : LREAL; (*Data for internal use.*)
		ScaledTargetDec : LREAL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentIntParType : 	STRUCT  (*Data for internal use.*)
		Step1Done : BOOL; (*Data for internal use.*)
		Step2Done : BOOL; (*Data for internal use.*)
		Step3Done : BOOL; (*Data for internal use.*)
		DeltaActPosition : REAL; (*Data for internal use.*)
		DeltaSetPosition : REAL; (*Data for internal use.*)
		PositionAtStep : REAL; (*Data for internal use.*)
		VelocityAtStep : REAL; (*Data for internal use.*)
		PosDir : MTHydGenProfIdentIntParDirType; (*Data for internal use.*)
		NegDir : MTHydGenProfIdentIntParDirType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentIntParDirType : 	STRUCT  (*Data for internal use.*)
		MaxCylPosition : REAL; (*Data for internal use.*)
		EndCylPosition : REAL; (*Data for internal use.*)
		SetVelocity : REAL; (*Data for internal use.*)
		K : REAL; (*Data for internal use.*)
		aRamp : MTHydGenProfIdentIntRampType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentIntRampType : 	STRUCT  (*Data for internal use.*)
		Value : REAL; (*Data for internal use.*)
		UserValue : REAL; (*Data for internal use.*)
		EnableUserValue : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentIntDTParType : 	STRUCT  (*Data for internal use.*)
		PosDir : MTHydGenProfIdentIntDTParDirType; (*Data for internal use.*)
		NegDir : MTHydGenProfIdentIntDTParDirType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentIntDTParDirType : 	STRUCT  (*Data for internal use.*)
		Done : BOOL; (*Data for internal use.*)
		Index : USINT; (*Data for internal use.*)
		NumTestValues : USINT; (*Data for internal use.*)
		Velocity : REAL; (*Data for internal use.*)
		MaxPosition : REAL; (*Data for internal use.*)
		rSet : REAL; (*Data for internal use.*)
		Top : MTHydGenProfIdentIntDTTupleType; (*Data for internal use.*)
		Try : MTHydGenProfIdentIntDTTupleType; (*Data for internal use.*)
		Bottom : MTHydGenProfIdentIntDTTupleType; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfIdentIntDTTupleType : 	STRUCT  (*Data for internal use.*)
		DeadTime : REAL; (*Data for internal use.*)
		Deviation : REAL; (*Data for internal use.*)
		MaxDeviation : REAL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfileIdentInternalType : 	STRUCT  (*Data for internal use.*)
		CycleTime : LREAL; (*Task cycle time. Unit: [s].*)
		InhibitUpdate : BOOL; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		StartIdentificationOld : BOOL; (*Data for internal use.*)
		StopIdentificationOld : BOOL; (*Data for internal use.*)
		RunIdentification : BOOL; (*Data for internal use.*)
		StopWithRampActive : BOOL; (*Data for internal use.*)
		Parameters : MTHydGenProfileIdentParType; (*Data for internal use.*)
		Mode : MTHydGenProfileIdentModeEnum; (*Data for internal use.*)
		DeadTimeIdentification : MTHydGenProfileIdentDeadTimeType; (*Data for internal use.*)
		UpperVelocityLimit : REAL; (*Data for internal use.*)
		Timer : LREAL; (*Data for internal use.*)
		WaitingTime : LREAL; (*Data for internal use.*)
		StepIdentification : USINT; (*Data for internal use.*)
		StepIdentificationDeadTime : USINT; (*Data for internal use.*)
		Ident : MTHydGenProfIdentIntParType; (*Data for internal use.*)
		IdentDeadTime : MTHydGenProfIdentIntDTParType; (*Data for internal use.*)
		StartPositionTolerance : REAL; (*Data for internal use.*)
		StickingPositionTolerance : REAL; (*Data for internal use.*)
		Identified : MTHydGenProfIdentifiedParType; (*Data for internal use.*)
		TargetDecFactor : REAL; (*Data for internal use.*)
		Statistics : MTHydGenProfileIdentStatType; (*Data for internal use.*)
		NextStep : USINT; (*Data for internal use.*)
		MoveToStartPosition : BOOL; (*Data for internal use.*)
		StatusIDUpdate : DINT; (*Data for internal use.*)
		MovingAverage : MTHydGenProfileIdentMoveAvgType; (*Data for internal use.*)
		UseMaxPositionForIdentification : BOOL; (*Data for internal use.*)
	END_STRUCT;
	MTHydGenProfileIdentDTModeEnum : 
		( (*Mode of dead time identification.*)
		mtHYDGEN_DEADTIME_IDENT_OFF := 0, (*No identification of the dead time.*)
		mtHYDGEN_DEADTIME_IDENT_BASIC := 1, (*Identification of dead time with a basic functionality. *)
		mtHYDGEN_DEADTIME_IDENT_ADVANCED := 2 (*Identification of dead time with an advanced functionality. Is more accurate than basic, but in some cases not so robust.*)
		);
	MTHydGenProfileIdentModeEnum : 
		( (*Identification mode. Either the cylinder stops with a defined ramp or with a jump to 0 rpm of the pump.*)
		mtHYDGEN_STOP_WITH_RAMP := 0, (*Cylinder will stop with a ramp and the deceleration will be identified out of this ramp.*)
		mtHYDGEN_STOP_WITH_STEP := 1 (*Cylinder will stop with a step to zero and the deceleration will be identified out of this step.*)
		);
END_TYPE

(*Adaptive Position Correction Types*)

TYPE
	MTHydGenAdaptCorrParType : 	STRUCT  (*Parameters used for adaptive position correction.*)
		MaxPositionCorrection : REAL := 1.0; (*Maximum allowed position correction value. Unit: [mm]. Valid value range: MaxPositionCorrection > 0.*)
		PositionTolerance : REAL := 0.2; (*Absolut value of the allowed position tolerance. Unit: [mm]. Valid value range: PositionTolerance >= 0.*)
		NumMeanMovements : USINT := 3; (*Number of the last movements for adaptive position correction. Valid value range: 0 < NumMeanMovement <= 10.*)
		WaitingTime : REAL := 0.5; (*Waiting time after MovementDone for evaluating the position error. Unit: [s]. Valid value range: WatingTime >= 0.*)
	END_STRUCT;
	MTHydGenAdaptCorrInternalType : 	STRUCT  (*Structure of internal parameters.*)
		CycleTime : LREAL; (*Task cycle time. Unit: [s].*)
		InhibitUpdate : BOOL; (*Data for internal use.*)
		Parameters : MTHydGenAdaptCorrParType; (*Data for internal use.*)
		ParametersValid : BOOL; (*Data for internal use.*)
		UpdateOld : BOOL; (*Data for internal use.*)
		EnableOld : BOOL; (*Data for internal use.*)
		StatusIDUpdate : DINT; (*Data for internal use.*)
		ActPosError : REAL; (*Data for internal use.*)
		MovementDoneOld : BOOL; (*Data for internal use.*)
		ResetCorrectionOld : BOOL; (*Data for internal use.*)
		corr_vals : ARRAY[0..9]OF REAL; (*Data for internal use.*)
		a : ARRAY[0..9]OF REAL; (*Data for internal use.*)
		SettlingPhase : BOOL; (*Data for internal use.*)
		index : USINT; (*Data for internal use.*)
		MeanError : REAL; (*Data for internal use.*)
		t : REAL; (*Data for internal use.*)
		SetPositionOld : REAL; (*Data for internal use.*)
		i : USINT; (*Data for internal use.*)
	END_STRUCT;
END_TYPE
